# Generated by Django 5.2.1 on 2025-06-26 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookimport', '0002_alter_book_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdditionalAuthor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=200, unique=True)),
                ('author2', models.CharField(blank=True, max_length=200)),
                ('author3', models.CharField(blank=True, max_length=200)),
                ('author4', models.CharField(blank=True, max_length=200)),
                ('author5', models.CharField(blank=True, max_length=200)),
                ('author6', models.CharField(blank=True, max_length=200)),
                ('author7', models.CharField(blank=True, max_length=200)),
                ('author8', models.CharField(blank=True, max_length=200)),
                ('author9', models.CharField(blank=True, max_length=200)),
                ('author10', models.CharField(blank=True, max_length=200)),
            ],
        ),
    ]
